branches:
  only:
    - /[0-9]*.0/
language: c
arch: amd64
os: linux
dist: xenial
addons:
  apt:
    packages:
      - subversion 
      - ccache 
      - texlive 
      - texlive-fonts-extra 
      - texlive-latex-extra
      - libx11-dev
      - libpcre2-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libxmu-dev
      - libxt-dev
      - libreadline-dev
      - zstd

script:
  - sudo apt -qq build-dep r-base -y
  - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
  - sudo apt -qq update
  - sudo apt -qq install intel-mkl-2020.3-111
  - mkdir ../R-MKL/ && cd ../R-MKL/
  - wget "${ICCDL}" -q
  - tar -I zstd -xf ${ICCTARBALL} && rm ${ICCTARBALL}
  - export PATH=/home/travis/build/MitsuhaMiyamizu/R-MKL/intel/bin/:$PATH
  - export INTEL_LICENSE_FILE=/home/travis/build/MitsuhaMiyamizu/R-MKL/intel/
  - source /opt/intel/mkl/bin/mklvars.sh intel64
  - export _intel_arch=intel64
  - export _intel_lib=mkl_intel_lp64
  - export MKL="-L${MKLROOT}/lib/intel64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lmkl_rt -lpthread -lm -ldl"
  - export _intel_cc_opt="-O3 -fPIC -m64 -march=native -fp-model precise -fp-model source -I${MKLROOT}/include"
  - export LDFLAGS="-qopenmp"
  - export CFLAGS="${_intel_cc_opt}"
  - export CXXFLAGS="${_intel_cc_opt}"
  - export FFLAGS="${_intel_cc_opt}"
  - export FCFLAGS="${_intel_cc_opt}"
  - export CC="icc"
  - export CXX="icpc"
  - export F77="ifort"
  - export FC="ifort"
  - export AR="xiar"
  - export LD="xild"
  - export LD_LIBRARY_PATH=/home/travis/build/MitsuhaMiyamizu/R-MKL/intel/compilers_and_libraries_2020.3.275/linux/compiler/lib/intel64_lin/
  - source /home/travis/build/MitsuhaMiyamizu/R-MKL/intel/bin/compilervars.sh ${_intel_arch}
  - wget "https://github.com/MitsuhaMiyamizu/R-MKL/releases/download/1.0.bionic/R-4.0.2.tar.zst" -q
  - tar -I zstd -xf R-4.0.2.tar.zst && rm R-4.0.2.tar.zst
  - cd R-4.0.2/
  - sudo -E env "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" env "PATH=$PATH" make install
  - cd ..
  - mkdir /home/travis/build/MitsuhaMiyamizu/R-MKL/R/
  - mkdir /home/travis/build/MitsuhaMiyamizu/R-MKL/R/library/
  - cd ../R-pkg/
  - Rscript pkg2.R
  - tar -I zstd -cf pkg.tar.zst /home/travis/build/MitsuhaMiyamizu/R-MKL/R/
deploy:
  provider: releases
  token: ${pkg_key}
  skip_cleanup: true
  file: pkg.tar.zst
  overwrite: true
  on:
    tags: true
    all_branches: true
    repo: MitsuhaMiyamizu/R-pkg
