.libPaths('/home/runner/work/R-pkg/R/library/')
repos <- 'https://cloud.r-project.org/'
install.packages("foreach", repos = repos)
install.packages("doParallel", repos = repos)
install.packages("SuppDists", repos = repos)
install.packages("dplyr", repos = repos)
install.packages("git2r", repos = repos)
install.packages("tidyr", repos = repos)
install.packages("ggplot2", repos = repos)
install.packages("plotly", repos = repos)
install.packages("tibble", repos = repos)
install.packages("stringr", repos = repos)
install.packages("lme4", repos = repos)
install.packages("pdftools", repos = repos)
install.packages("xgboost", repos = repos)
install.packages("gbm", repos = repos)
install.packages("glmnet", repos = repos)
install.packages("caret", repos = repos)
install.packages("randomForest", repos = repos)
install.packages("fgsea", repos = repos)
install.packages("ranger", repos = repos)
install.packages("pROC", repos = repos)
install.packages("devtools", repos = repos)
install.packages("NMF", repos = repos)
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager", repos = repos)
BiocManager::install("clusterProfiler")
