name: pkg
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Setup env
        uses: actions/checkout@v2
      - name: Download toolchain
        env:
          iccdl: ${{ secrets.ICCDLADDR }}
        run: |
          cd /home/runner/work/R-pkg/
          wget ${iccdl} -q
          tar xzf intel.tar.gz
          rm intel.tar.gz
      - name: Install dependencies
        run: sudo apt-get -qq update
      - name: Install dependencies 1
        run: |
          sudo apt-get install subversion ccache texlive texlive-fonts-extra texlive-latex-extra libx11-dev libpcre2-dev libjpeg-dev libpng-dev libtiff-dev libxmu-dev libxt-dev libreadline-dev
          curl https://repogen.simplylinux.ch/txt/xenial/sources_8e2c2611bccddbabe97e129f805006bdfd8ee22b.txt | sudo tee /etc/apt/sources.list
          sudo apt-get -qq update
          sudo apt-get -qq build-dep r-base -y
          cd /home/runner/work/R-pkg/
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
          sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
      - name: Install intel mkl library
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install intel-mkl-2020.0-088 -y
      - name: Prepare R source tarball
        run: |
          cd /home/runner/work/R-pkg/
          bash ./env.sh
          wget "https://cran.r-project.org/src/base/R-4/R-4.0.2.tar.gz" -q
          tar zxf R-4.0.2.tar.gz && rm R-4.0.2.tar.gz
          cd R-4.0.2/
          ./configure --prefix=/usr --libdir=/usr/lib --sysconfdir=/etc/R --datarootdir=/usr/share rsharedir=/usr/share/R/ rincludedir=/usr/include/R/ rdocdir=/usr/share/doc/R/ --with-x --enable-R-shlib --with-blas="$MKL" --with-lapack --disable-R-profiling --with-tcltk
      - name: Compile R
        run: |
          bash ./env.sh
          cd /home/runner/work/R-pkg/R-4.0.2/
          make
      - name: Install & Benchmark
        run: |
          bash ./env.sh
          cd /home/runner/work/R-pkg/R-4.0.2/
          cd .. && tar cvf R-4.0.2.tar.gz R-4.0.2/
          cd R-4.0.2/
          sudo -E env "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" env "PATH=$PATH" make install
          Rscript pkg.R
          Rscript R-benchmark.R
          Rscript dgemm.R
          Rscript parallel.R
          Rscript multitest.R
          cat bench-25.R | time R --slave --no-save
