name: pkg
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup env
        uses: actions/checkout@v2
      - name: Download toolchain
        env:
          iccdl: ${{ secrets.ICCDLADDR }}
          icctar: ${{ secrets.ICCTARBALL }}
        run: |
          sudo apt-get -qq install zstd
          cd /home/runner/work/R-pkg/
          wget ${iccdl} -q
          tar -I zstd -xf ${icctar}
          rm ${icctar}
      - name: Install dependencies 1
        run: |
          sudo apt-get install subversion ccache texlive texlive-fonts-extra texlive-latex-extra libx11-dev libpcre2-dev libjpeg-dev libpng-dev libtiff-dev libxmu-dev libxt-dev libreadline-dev -y
          curl https://repogen.simplylinux.ch/txt/bionic/sources_dd16190d58c2ce272cf1b15983db2daaa096d075.txt | sudo tee /etc/apt/sources.list
          sudo apt-get -qq update
          sudo apt-get -qq build-dep r-base -y
          cd /home/runner/work/R-pkg/
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
          sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
      - name: Install intel mkl library
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install intel-mkl-2020.3-111 -y
      - name: Prepare R source tarball
        run: |
          cd /home/runner/work/R-pkg/
          wget "https://github.com/MitsuhaMiyamizu/R-MKL/releases/download/v4.0.2.bionic/R.tar.zst" -q
      - name: Decompress R
        run: |
          cd /home/runner/work/R-pkg/ && tar -I zstd -xf R.tar.zst
          rm R.tar.zst
      - name: Install & Benchmark
        run: |
          export PATH=/home/runner/work/R-pkg/intel/bin/:$PATH
          export INTEL_LICENSE_FILE=/home/runner/work/R-pkg/intel
          source /opt/intel/mkl/bin/mklvars.sh intel64
          export _intel_arch=intel64
          export _intel_lib=mkl_intel_lp64
          export MKL="-L${MKLROOT}/lib/intel64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lmkl_rt -lpthread -lm -ldl"
          export _intel_cc_opt="-O3 -fPIC -m64 -march=native -fp-model precise -fp-model source -I${MKLROOT}/include"
          export LDFLAGS="-qopenmp"
          export CFLAGS="${_intel_cc_opt}"
          export CXXFLAGS="${_intel_cc_opt}"
          export FFLAGS="${_intel_cc_opt}"
          export FCFLAGS="${_intel_cc_opt}"
          export CC="icc"
          export CXX="icpc"
          export F77="ifort"
          export FC="ifort"
          export AR="xiar"
          export LD="xild"
          export LD_LIBRARY_PATH=/home/runner/work/R-pkg/intel/compilers_and_libraries_2020.3.275/linux/compiler/lib/intel64_lin/
          source /home/runner/work/R-pkg/intel/bin/compilervars.sh ${_intel_arch}
          cd /home/runner/work/R-pkg/R-4.0.2/
          mkdir /home/runner/work/R-pkg/R/
          mkdir /home/runner/work/R-pkg/R/library/
          cd /home/runner/work/R-pkg/R-4.0.2/
          sudo -E env "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" env "PATH=$PATH" make install
          cd /home/runner/work/R-pkg/R-pkg/
          Rscript pkg.R
          cd /home/runner/work/R-pkg/ && tar -I zstd -cf pkg.tar.zst R/
          mv pkg.tar.zst /home/runner/work/R-pkg/R-pkg/
          ls -al /home/runner/work/R-pkg/
          cd /home/runner/work/R-pkg/R-pkg/
          export RELEASE_TAG=$(git tag -l)
      - name: Upload Binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/R-pkg/R-pkg/pkg.tar.zst
          tag: v4.0.2.pkg.bionic
          overwrite: true
          file_glob: true
